baseURL = "https://plan4better.de/"
defaultContentLanguage = "de"
languageCode = "en-us"
title = "Plan4Better"
[languages.de]
contentDir = "content/de"
languageName = "German"
title = "Plan4Better"
weight = 2
[[languages.de.menu.center]]
name = "GOAT"
url = "/"
weight = 1
[languages.de.menu.center.params]
heading = "Geo Open Accessibility Tool - GOAT"
text = "GOAT ist ein interaktives Webtool für die Erstellung von Erreichbarkeitsanalysen für den Fuß-, Radverkehr und ÖPNV, sowie die Stadt- und Quartiersplanung. Detaillierte Infos finden Sie auf den folgenden Seiten."
[[languages.de.menu.center]]
name = "GOAT für Städte und Regionen"
parent = "GOAT"
url = "/goat/"
weight = 2
[[languages.de.menu.center]]
name = "GOAT für Planungsbüros"
parent = "GOAT"
url = "/goat-consulting/"
weight = 3
[[languages.de.menu.center]]
name = "Einsatzmöglichkeiten"
parent = "GOAT"
url = "/goat-anwendung/"
weight = 5
[[languages.de.menu.center]]
name = "Videos"
parent = "GOAT"
url = "/videos/"
weight = 6
[[languages.de.menu.center]]
name = "Tutorials"
parent = "GOAT"
url = "/tutorials/isochrone/"
weight = 7
[[languages.de.menu.center]]
name = "Docs"
parent = "GOAT"
url = "/docs/background/"
weight = 8
[[languages.de.menu.center]]
name = "Competences"
weight = 2
[languages.de.menu.center.params]
heading = "Duis aute irure dolor2"
hidden = true
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua2."
[[languages.de.menu.center]]
name = "Competences Overview"
parent = "Competences"
url = "/competences-overview/"
weight = 2
[[languages.de.menu.center]]
name = "Web-GIS"
parent = "Competences"
url = "/web-gis/"
weight = 3
[[languages.de.menu.center]]
name = "Trainings"
parent = "Competences"
url = "/trainings/"
weight = 4
[[languages.de.menu.center]]
name = "Consultancy"
parent = "Competences"
url = "/consultancy/"
weight = 5
[[languages.de.menu.center]]
name = "Über uns"
url = "/"
weight = 3
[languages.de.menu.center.params]
heading = "Plan4Better - Über uns"
text = "Wir sind Plan4Better - ein diverses Team aus Umweltingenieur:innen, GIS-Entwickler:innen und Verkehrsplaner:innen, vereint durch die Motivation einen Beitrag zur nachhaltigen Stadt- und Verkehrsplanung zu leisten. "
[[languages.de.menu.center]]
name = "Team"
parent = "Über uns"
url = "/team/"
weight = 4
[[languages.de.menu.center]]
name = "Mission"
parent = "Über uns"
url = "/mission/"
weight = 5
[[languages.de.menu.center]]
name = "Presse"
parent = "Über uns"
url = "/presse/"
weight = 7
[[languages.de.menu.center]]
name = "Blog"
url = "/blog/"
weight = 6
[[languages.de.menu.center]]
name = "Kontakt"
url = "/kontakt/"
weight = 8
[[languages.de.menu.center]]
name = "Referenzen"
url = "/references/"
weight = 7
[[languages.en.menu.center]]
name = "References"
url = "/references/"
weight = 7
[[languages.de.menu.footer]]
name = "Kontakt"
url = "/kontakt/"
weight = 1
[[languages.de.menu.footer]]
name = "Impressum"
url = "/imprint/"
weight = 2
[[languages.de.menu.footer]]
name = "Datenschutzerklärung"
url = "/privacy/"
weight = 3
[[languages.de.menu.footer]]
name = "Datenschutzhinweise Social Media"
url = "/privacy_social_media/"
weight = 4
[[languages.de.menu.footer]]
name = "Nutzungsbedingungen"
url = "/nutzungsbedingungen/"
weight = 5
[[languages.de.menu.right]]
name = "Login / Für Demo registrieren"
url = "/request-demo/"
weight = 1
[languages.de.menu.right.params]
button = "primary-outline"
[[languages.de.menu.social]]
name = "Twitter"
url = "https://twitter.com/plan4better"
weight = 1
[languages.de.menu.social.params]
icon = "twitter"
[[languages.de.menu.social]]
name = "Linkedin"
url = "https://www.linkedin.com/company/plan4better/"
weight = 2
[languages.de.menu.social.params]
icon = "linkedin"
[[languages.de.menu.social]]
name = "GitHub"
url = "https://github.com/goat-community/"
weight = 3
[languages.de.menu.social.params]
icon = "github"
[languages.en]
contentDir = "content/en"
languageName = "English"
title = "Plan4Better"
weight = 1
[[languages.en.menu.center]]
name = "GOAT"
url = "/"
weight = 1
[languages.en.menu.center.params]
heading = "Geo Open Accessibility Tool - GOAT"
text = "GOAT is an interactive webtool for accessibility analysis on walking and cycling. Find out more by visiting the subpages."
[[languages.en.menu.center]]
name = "GOAT for cities and regions"
parent = "GOAT"
url = "/en/goat/"
weight = 2
[[languages.en.menu.center]]
name = "GOAT for planning offices"
parent = "GOAT"
url = "/en/goat-consulting/"
weight = 3
[[languages.en.menu.center]]
name = "Use Cases"
parent = "GOAT"
url = "/goat-application"
weight = 5
[[languages.en.menu.center]]
name = "Videos"
parent = "GOAT"
url = "/videos/"
weight = 6
[[languages.en.menu.center]]
name = "Tutorials"
parent = "GOAT"
url = "/tutorials/isochrone/"
weight = 7
[[languages.en.menu.center]]
name = "Docs"
parent = "GOAT"
url = "/docs/background/"
weight = 8
[[languages.en.menu.center]]
name = "Competences"
weight = 2
[languages.en.menu.center.params]
heading = "Duis aute irure dolor2"
hidden = true
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua2."
[[languages.en.menu.center]]
name = "Heading 3"
parent = "Competences"
weight = 1
[[languages.en.menu.center]]
name = "Competences Overview"
parent = "Competences"
url = "/competences-overview/"
weight = 2
[[languages.en.menu.center]]
name = "Web-GIS"
parent = "Competences"
url = "/web-gis/"
weight = 3
[[languages.en.menu.center]]
name = "Trainings"
parent = "Competences"
url = "/trainings/"
weight = 4
[[languages.en.menu.center]]
name = "Consultancy"
parent = "Competences"
url = "/consultancy/"
weight = 5
[[languages.en.menu.center]]
name = "Heading 4"
parent = "Competences"
pre = "2"
weight = 6
[[languages.en.menu.center]]
name = "Link 4"
parent = "Competences"
pre = "2"
url = "/link4/"
weight = 7
[[languages.en.menu.center]]
name = "Link 5"
parent = "Competences"
pre = "2"
url = "/link5/"
weight = 8
[[languages.en.menu.center]]
name = "Link 6"
parent = "Competences"
pre = "2"
url = "/link6/"
weight = 9
[[languages.en.menu.center]]
name = "About us"
url = "/"
weight = 3
[languages.en.menu.center.params]
heading = "About us"
text = "We are Plan4Better - a diverse team of environmental engineers, GIS developers and transport planners united by the motivation to contribute to sustainable urban and transport planning."
[[languages.en.menu.center]]
name = "Team"
parent = "About us"
url = "/en/team/"
weight = 4
[[languages.en.menu.center]]
name = "Mission"
parent = "About us"
url = "/mission/"
weight = 5
[[languages.en.menu.center]]
name = "Press"
parent = "About us"
url = "/press/"
weight = 7
[[languages.en.menu.center]]
name = "Blog"
url = "/blog/"
weight = 6
[[languages.en.menu.center]]
name = "Contact"
url = "/en/contact/"
weight = 8
[[languages.en.menu.footer]]
name = "Contact us"
url = "/en/contact/"
weight = 1
[[languages.en.menu.footer]]
name = "Imprint"
url = "/imprint/"
weight = 2
[[languages.en.menu.footer]]
name = "Privacy"
url = "/privacy/"
weight = 3
[[languages.en.menu.footer]]
name = "Privacy Social Media"
url = "/privacy_social_media/"
weight = 4
[[languages.en.menu.footer]]
name = "Terms of use"
url = "/nutzungsbedingungen/"
weight = 5
[[languages.en.menu.right]]
name = "Login / Get Demo"
url = "/request-demo/"
weight = 1
[languages.en.menu.right.params]
button = "primary-outline"
[[languages.en.menu.social]]
name = "Twitter"
url = "https://twitter.com/plan4better"
weight = 1
[languages.en.menu.social.params]
icon = "twitter"
[[languages.en.menu.social]]
name = "Linkedin"
url = "https://www.linkedin.com/company/plan4better/"
weight = 2
[languages.en.menu.social.params]
icon = "linkedin"
[[languages.en.menu.social]]
name = "GitHub"
url = "https://github.com/goat-community/"
weight = 3
[languages.en.menu.social.params]
icon = "github"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"
[markup.tableOfContents]
endLevel = 2
startLevel = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]
[params]
address = "Am Kartoffelgarten 14 c/o WERK1 <br>81671 München <br>Germany"
email = "info@plan4better.de"
mailchimp_form_action = ""
mailchimp_hidden_name = ""
ogimage = "/images/request-demo/request_demo_ogimage.png"
twitter = "@plan4better"
phone = "+49 89 2000 708 30"
site_logo = "images/logo.png"
site_logo_light = "images/logo-light.png"
[taxonomies]
author = "author"
categories = "categories"
